import crypto from "node:crypto";
import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { intakeSchema,buildIntakePendingItems } from "@/lib/intake";
import { sameOriginStrict } from "@/lib/security";
import { isRateLimited, recordFailure } from "@/lib/rate-limit";
const hash=(t:string)=>crypto.createHash("sha256").update(t).digest("hex");
async function auth(id:string,token:string){if(!token)return null;const sql=db();const rows=await sql`SELECT * FROM invitation_intakes WHERE id=${id} AND public_token_hash=${hash(token)} LIMIT 1`;return rows[0]||null;}
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const token=request.headers.get("x-intake-token")||new URL(request.url).searchParams.get("token")||"";const row:any=await auth(id,token);if(!row)return NextResponse.json({message:"Acesso inválido."},{status:403});await db()`UPDATE invitation_intakes SET last_opened_at=now() WHERE id=${id}`;return NextResponse.json({id:row.id,event_type:row.event_type,status:row.status,contact_name:row.contact_name,whatsapp:row.whatsapp,email:row.email||"",event_date_defined:row.event_date_defined,event_date:row.event_date?String(row.event_date).slice(0,10):"",event_time:row.event_time?String(row.event_time).slice(0,5):"",answers:row.answers||{},visual_direction:row.visual_direction||{},pending_items:row.pending_items||[],locked:Boolean(row.converted_event_id)||row.status==="converted"});}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){if(!sameOriginStrict(request))return NextResponse.json({message:"Origem inválida."},{status:403});if(await isRateLimited(request,null,"public_intake_edit",30,60))return NextResponse.json({message:"Muitas alterações em pouco tempo. Aguarde alguns minutos."},{status:429});await recordFailure(request,null,"public_intake_edit");const {id}=await params;const body=await request.json().catch(()=>null);const token=String(body?.access_token||"");const row:any=await auth(id,token);if(!row)return NextResponse.json({message:"Acesso inválido."},{status:403});if(row.converted_event_id||row.status==="converted")return NextResponse.json({message:"Esta ficha já entrou em produção e não pode mais ser alterada por este link."},{status:409});const parsed=intakeSchema.safeParse(body?.data);if(!parsed.success)return NextResponse.json({message:parsed.error.issues[0]?.message||"Confira os dados."},{status:400});const v=parsed.data;const answers={identity:v.identity,age:v.age??null,location_defined:v.location_defined,venue:v.venue,address:v.address,city:v.city,maps_url:v.maps_url,rsvp_wanted:v.rsvp_wanted,gifts_wanted:v.gifts_wanted,dress_code_wanted:v.dress_code_wanted,schedule_wanted:v.schedule_wanted,important_info:v.important_info,required_message:v.required_message,wedding_hosting:v.wedding_hosting,bride_parents:v.bride_parents,groom_parents:v.groom_parents,wedding_venues:v.wedding_venues,reception_venue:v.reception_venue,reception_address:v.reception_address,reception_city:v.reception_city,special_text_choice:v.special_text_choice,special_text:v.special_text,invite_photo_choice:v.invite_photo_choice,invite_photo_drive_url:v.invite_photo_drive_url,event_specific:v.event_specific};const visual={decoration_status:v.decoration_status,decoration_notes:v.decoration_notes,style_tags:v.style_tags,color_notes:v.color_notes,style_notes:v.style_notes,selected_colors:v.selected_colors};await db()`UPDATE invitation_intakes SET event_type=${v.event_type},contact_name=${v.contact_name},whatsapp=${v.whatsapp},email=${v.email||null},event_date=${v.event_date||null}::date,event_date_defined=${v.event_date_defined},event_time=${v.event_time||null}::time,answers=${JSON.stringify(answers)}::jsonb,visual_direction=${JSON.stringify(visual)}::jsonb,pending_items=${JSON.stringify(buildIntakePendingItems(v))}::jsonb,updated_at=now() WHERE id=${id}`;return NextResponse.json({ok:true});}